// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYEgeP7yPZunN3yrUduimgdtHQsAn26jc',
    appId: '1:880908733118:web:4278eb5d49d6548e3becef',
    messagingSenderId: '880908733118',
    projectId: 'cinegeek-22eb7',
    authDomain: 'cinegeek-22eb7.firebaseapp.com',
    storageBucket: 'cinegeek-22eb7.firebasestorage.app',
    measurementId: 'G-8RYVHPXK38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_4N2fK_rUMpCsLzgeCsAjpy2I94Yfjg',
    appId: '1:880908733118:android:b501d2e8a63b6ce53becef',
    messagingSenderId: '880908733118',
    projectId: 'cinegeek-22eb7',
    storageBucket: 'cinegeek-22eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJRjAFIfXQLfcp90aecQ56XHjz70CY4A',
    appId: '1:880908733118:ios:c62ceb93eb61b51f3becef',
    messagingSenderId: '880908733118',
    projectId: 'cinegeek-22eb7',
    storageBucket: 'cinegeek-22eb7.firebasestorage.app',
    iosBundleId: 'com.example.cinegeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJRjAFIfXQLfcp90aecQ56XHjz70CY4A',
    appId: '1:880908733118:ios:c62ceb93eb61b51f3becef',
    messagingSenderId: '880908733118',
    projectId: 'cinegeek-22eb7',
    storageBucket: 'cinegeek-22eb7.firebasestorage.app',
    iosBundleId: 'com.example.cinegeek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYEgeP7yPZunN3yrUduimgdtHQsAn26jc',
    appId: '1:880908733118:web:75d04085f7c7873d3becef',
    messagingSenderId: '880908733118',
    projectId: 'cinegeek-22eb7',
    authDomain: 'cinegeek-22eb7.firebaseapp.com',
    storageBucket: 'cinegeek-22eb7.firebasestorage.app',
    measurementId: 'G-H22K96VBGF',
  );
}
